apps/user/urls.py
from django.urls import path
from apps.user.views import *
from apps.srea.vistas.facultad import*
from apps.user.vistas.carerra import*
from apps.user.vistas.ficha import*
from apps.user.vistas.indicacion import*


from django.contrib.auth.decorators import login_required

app_name="apps.user" #Variable que me permite decir como se va a llamar la ruta que se va a concatenar con la otra ruta absoluta

urlpatterns = [
#-------------------------Usuario---------------------------------------
    path('user_list/',(UserListView.as_view()), name="user_list"),
    path('user/', (UserCreateView.as_view()), name="user"),
    path('user_list/u_user/<int:pk>/', UserUpdateView.as_view(), name="u_user"),
    path('user_list/d_user/<int:pk>/', UserDeleteView.as_view(), name="d_user"),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('perfil/', UserProfileView.as_view(), name='editar_perfil'),
    path('password/', UserChangePasswordView.as_view(), name='cambiar_clave'),

    ########################################################################3
    path('user/login', (UserCreateView2.as_view()), name="user_login"),
#-------------------------Facultad---------------------------------------
    path('facultad_list/',(FacultadListView.as_view()), name="facultad_list"),
    path('facultad/', (FacultadCreateView.as_view()), name="facultad"),
    path('facultad_list/u_facultad/<int:pk>/', FacultadUpdateView.as_view(), name="u_facultad"),
    path('facultad_list/d_facultad/<int:pk>/', FacultadDeleteView.as_view(), name="d_facultad"),

#-------------------------Carrera---------------------------------------
    path('carrera_list/',(CarreraListView.as_view()), name="carrera_list"),
    path('carrera/', (CarreraCreateView.as_view()), name="carrera"),
    path('carrera_list/u_carrera/<int:pk>/', CarreraUpdateView.as_view(), name="u_carrera"),
    path('carrera_list/d_carrera/<int:pk>/', CarreraDeleteView.as_view(), name="d_carrera"),

    #-------------------------Ficha---------------------------------------
    path('ficha_list/',(FichaListView.as_view()), name="ficha_list"),
    path('ficha/', (FichaCreateView.as_view()), name="ficha"),
    path('ficha_list/u_ficha/<str:uuid>/',FichaUpdateView.as_view(), name="u_ficha"),
     path('ficha_list/actualizar_ficha/<str:uuid>/',FichaUsuarioView.as_view(), name="usuario_ficha"),
    path('ficha_list/d_ficha/<str:uuid>/', FichaDeleteView.as_view(), name="d_ficha"),

    ###################################PDF###########################################
     path('ficha_list/pdf/<str:uuid>/', FichaPdfView.as_view(), name="ficha_pdf"),

     ###################################Inicaciones###########################################
     path('indicacion/', IndicacionListView.as_view(), name="ayuda"),

    #path('indicacion/<indicacion_id>', AyudaLista, name="lista-ayuda"),


]

core/urls.py
from django.contrib import admin #Librería de adminitración
from django.urls import path, include #Librería permite incluir las urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.login.urls'),  name='login1'),
    path('admin/', admin.site.urls),#Al inicio cargamos el administrador de Django
    path('accounts/', include('allauth.urls')),
    path('srea/',include('apps.srea.urls', namespace='srea')),
    path('user/',include('apps.user.urls', namespace='user')),
    path('quiz/',include('apps.quiz.urls', namespace='quiz')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #Configuracón para que se puedan leer los archivos

apps/user/views.py
from django.views.generic import* #importando la vista genérica
from apps.srea.models import* #importando los modelos
from apps.user.models import* #importando los modelos
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator #importando el método decorador
from django.http import *
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from apps.user.forms import*
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.srea.mixins import*
from apps.srea.forms import*
from django.contrib.auth.models import Group
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash



class UserListView(LoginRequiredMixin,ValidatePermissionRequiredMixin,ListView): #Primera vista basada en clase ListView, permite sobrescribir métodos
    context_object_name = 'matricula'
    model= User#Primero se indica el modelo o entidad
    template_name = 'user/user_lista.html' #Indicarle cual es la plantilla
    permission_required='view_user'
    
    @method_decorator(csrf_exempt)#Desactivando el mecanismo de defensa de django
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):###Implementación de ajax en mi método sobrescrito POST###
        data={} #Se declara un diccionario llamado data
        try: #controlar el error
            action=request.POST['action']
            if action == 'searchdata':
                data=[]
                position = 1
                if request.user.is_staff :
                    for i in User.objects.all():
                        item= i.toJSON()
                        item['position']=position
                        data.append(item)#Incrusto cada uno de mis elementos dentro de mi array
                        position+=1
                if  not request.user.is_staff:
                     user=User.objects.filter(pk=request.user.pk)
                     for u in user:
                         for c in Ciclo.objects.filter(curso=u.id):
                            for i  in User.objects.filter(curso=c.id):
                            #   print(a)
                                item= i.toJSON()
                                item['position']=position
                                data.append(item)#Incrusto cada uno de mis elementos dentro de mi array
                                position+=1
            else:
                data["error"]='Ha ocurrido un error'
        except Exception as e: #Llamamos a la clase Exceptio para indicar el error
            data['error']=str(e) #Me devuelve el objeto e-->convertido a un string
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs): #Método que devuelve un diccionario que representa el contexto de la plantilla
        context = super().get_context_data(**kwargs) #Obtengo el diccionario que devuelve el método
        context['title']='Listado de Usuarios' #Puedo enviar variables
        context['url_create_login']=reverse_lazy('user:user_login')#Ruta abosluta creación de usuario
        context['url_create']=reverse_lazy('user:user')#Ruta abosluta creación de usuario
        context['url_list']=reverse_lazy('user:user_list')#Ruta abosluta lista de usuario
        context['date_now']=datetime.now() #Se obtiene la fecha de hoy
        context['modelo']='Usuarios'#Nombre de identidad
        return context


class UserCreateView(LoginRequiredMixin,ValidatePermissionRequiredMixin,CreateView):
    model=User #Indicar el modelo con el cual se va ha trabajar
    form_class=UserCreateForm #Importando el formulario con el que voy a trabajar
    template_name='user/user_create.html' # Debo indicarle la ubicación de mi plantilla
    success_url= reverse_lazy('user:user_list') #Me permite direccionar a otra plantilla, la funnción reverse_lazy me recibe una url como parámetro
    permission_required='add_user'
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):###Implementación de ajax en mi método sobrescrito POST###
        data={} #Se declara un diccionario llamado data
        try: #controlar el error
            action= request.POST['action']#Recupero la variable action en mi método POST, cada vez que se haga una petición
            if action=='add': #Se indica el proceso add
                form=self.get_form() #Llamamos a nuestro formulario
                if form.is_valid():# Preguntamos si nuestro formulario es valido
                    form.save()
                else:
                    data['error']=form.errors # Data va a hacer igual al formulario con los errores 
            else:
                data['error']='No ingreso por ninguna opción'
        except Exception as e: #Llamamos a la clase Exception para indicar el error
            data['error']=str(e) #Me devuelve el objeto e-->convertido a un string
        return JsonResponse(data)


    def get_context_data(self, **kwargs): #Método que devuelve un diccionario que representa el contexto de la plantilla
        context = super().get_context_data(**kwargs) #Obtengo el diccionario que devuelve el método
        context['title']='Creación de un usuario' #Puedo enviar variables
        context['modelo']='User'#Nombre de identidad
        context['url_list']=self.success_url#Ruta abosluta lista de asignatura
        context['action']='add'#Enviar variable action
        return context

class UserUpdateView(LoginRequiredMixin,ValidatePermissionRequiredMixin,UpdateView):
    model = User #Indicar el modelo con el cual se va ha trabajar
    form_class = UserCreateForm #Importando el formulario con el que voy a trabajar
    template_name = 'user/user_create.html' #Debo indicarle la ubicación de mi plantilla
    success_url = reverse_lazy('user:user_list') #Me permite direccionar a otra plantilla, la función reverse_lazy me recibe una url como parámetro
    #@method_decorator(csrf_exempt) #Mecanismo de defensa de django
    permission_required='change_user'
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()#Le decimos que la clase object va a hacer igual a lo que tenemos en lainstancia de nuestro objeto, para que el funcionamiento no se altere
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data ={}                                     
        try:
            action= request.POST['action']
            if action =='edit':
                form = self.get_form()
                data=form.save()
            else:
                data['error']='No realiza ninguna acción'
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)
        
    def get_context_data(self, **kwargs): #Método que devuelve un diccionario que representa el contexto de la plantilla
        context = super().get_context_data(**kwargs) #Obtengo el diccionario que devuelve el método
        context['title']='Actualización de un usuario' #Puedo enviar variables
        context['modelo']='User'#Nombre de identidad
        context['url_list']=self.success_url#Ruta abosluta lista de asignatura
        context['action']='edit'#Enviar variable action
        return context

class UserDeleteView(LoginRequiredMixin,ValidatePermissionRequiredMixin,DeleteView):
    model = User #Indicar el modelo con el cual se va ha trabajar
    template_name = 'user/user_delete.html' #Debo indicarle la ubicación de mi plantilla
    success_url= reverse_lazy('user:user_list')#Me permite direccionar a otra plantilla, la función reverse_lazy me recibe una url como parámetro
    permission_required='delete_user'
   
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object() #Le decimos que la clase object va a hacer igual a lo que tenemos en lainstancia de nuestro objeto, para que el funcionamiento no se altere
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {} #Creación de variable tipo diccionario
        try:
            self.object.delete()#La variabe self.object contiene la variable de mi objeto y puedo acceder a los métodos
        except Exception as e:
            data['error'] = str(e) # Si llega a ocurrir un error de la excepion se debe guaradar en la viable e
        return JsonResponse(data) #Retorno como respuesta un JsonResponse
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de un usuario'
        context['modelo'] = 'User'
        context['url_list'] = self.success_url
        return context

class UserChangeGroup(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        try:
            request.session['group'] = Group.objects.get(pk=self.kwargs['pk']) #Guardo la sesión que voy a utilizar
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('srea:index1'))

class UserProfileView(LoginRequiredMixin,UpdateView):
    model = User #Indicar el modelo con el cual se va ha trabajar
    form_class = UserProfileForm #Importando el formulario con el que voy a trabajar
    template_name = 'user/user_profile_create.html' #Debo indicarle la ubicación de mi plantilla
    success_url = reverse_lazy('srea:index1') #Me permite direccionar a otra plantilla, la función reverse_lazy me recibe una url como parámetro
    #@method_decorator(csrf_exempt) #Mecanismo de defensa de django
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()#Le decimos que la clase object va a hacer igual a lo que tenemos en lainstancia de nuestro objeto, para que el funcionamiento no se altere
        return super().dispatch(request, *args, **kwargs)

apps/user/templates/ayuda/ayuda.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
    


    {% block head_list %}
    <link href="{% static 'css/material-icons.css' %}" rel="stylesheet"><!--Bajar está librería-->
    <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    
    <!--  Scripts-->
    <script src="{% static 'js/jquery-2.1.1.min.js'%}"></script><!--Bajar está librería-->
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>

    {% endblock %}

{% endblock %}

{% block content %}
<div class="card card-primary">
  <div class="card-header">
      <h3 class="card-title">
      </h3>
  </div>
  <div class="card-body">
      <table class="table" id="data">
        <thead>
        {%block colums%}
          <div class="section">
            <h4>{{ course.nombre }}</h4>
            <div class="divider"></div>
          </div>

          <div class="row">

            <div class="col s3">
              <ul class="collection with-header">
                <li class="collection-header"><h4><i class="far fa-handshake"> Servicio de ayuda </i></h4></li>
<!--**********************************Configuración de la cuenta*************************************************-->  
                <ul class="collapsible">  
                    <li>
                      <div class="collapsible-header"><i class="fas fa-user-cog"></i><b>Configuración de la cuenta</b>
                      </div>
                      <div class="collapsible-body">
                        <div class="collection">                                              <!--Aquí se debe cargar el manu-->
                          <p><a href="{% url 'user:editar_perfil' %}" class="collection-item "> <i class="fas fa-user-edit"> Editar perfil</i></a>
                          </a> 
                          <a href="{% url 'user:cambiar_clave' %}" class="collection-item "> <i class="fas fa-lock"> Editar password</i></a>
                          </a></p>                                                                                           
                        </div> 
                      </div>
                    </li>
           
                </ul> 

                
                
                 
                
                
               


                           
              </ul>
            </div>

            <div class="col s9">              
              <div class="section">
                <h4>Preguntas frecuentes</h4>
                <ul class="collapsible">
                  {% for i in indicacion %}
                        <li>
                            <div class="collapsible-header"><i class="fa fa-question-circle"></i><b>{{ i.titulo }}</b>
                            </div>
                            <div class="collapsible-body">
                              <div class="collection">
                                <p>{{i.descripcion}}</p>                                                                                           
                              </div>
                              <div class="collection">
                                {% if  i.documento %}
                                    <a href="/media/{{i.documento}}" target="_blank"><p><i class="fas fa-book-open"></i> {{i.titulo}} <i style="font-size:15px" class="fa">&#xf019;</i></p></a>                                                                                           
                                 {% endif %}                  
                              </div> 
                              
                            </div>
                        </li>
                  {% endfor %}
                </ul>                
              </div>
            </div>
          </div> 
        {%endblock%}
        </thead>
        <tbody>
        {%block rows%}

        {%endblock%}
        </tbody>
      </table>
  </div>
</div>
{% endblock %}

apps/user/templates/ayuda/indicacion_create.html
{% extends 'formulario.html' %}
{% load static %}
{% block head_form  %}
    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
    <script src="{% static 'curso/forms.js' %}"></script>
{% endblock %}

apps/user/templates/ayuda/indicacion_estudiante.html
<style>
    .main_div{
      margin:55px 0;
      with:55%;
      margin:100px auto;
      
    }
    .feed_principal{
      margin-bottom:20px;
      padding-bottom:15px 20px 0;
      background:rgb(200, 200, 180);
      border-radius:5px;
    }
  
  
  
    .titulo_header{
      margin-bottom: 10px
      word-wrap: break-word;
    }
  
    .big{
      margin-right: 5px;
      margin-left: 0px;
      font-weight:bold;
      font-size:19px;
      display:inline;
      line-height: 1.3;
    }
    .feed_propieda{
      display:table;
      width:100%;
    }
    .feed_avatar{
      display:table-cell;
      width:45px;
    }
    .userAvatar{
      background-size:100%;
      position:relative;
      display:block;
      margin-right:15px;
      float:left;
      border-radius:50%;
      width: 35px;
      height:35px;
    }
    .feed_detalles{
      display: table-cell;
      vertical-align:middle;
    }
    .feed_meta{
      color:#b2b2b2;
    }
    .b_comentar{
      outline:none;
      border:none;
      padding:10px;
      blackground:#333;
  
      border-radius:10px;
      display:block;
      margin-right:7px 0;
    }
  </style>

apps/user/templates/ayuda/indicacion_lista.html
{% extends 'base_list.html' %}
{% load widget_tweaks %}
{% load static %}
{%block title%}Lista de Asignaturas{%endblock%}
{% block head_list %}
    
{% endblock %}
{%block colums%}
<tr>
    <th scope="col" style="width: 16%;">Usuario</th>
    <th scope="col" style="width: 16%;">Titulo</th>
    <th scope="col" style="width: 20%;">Descripción</th>
    <th scope="col" style="width: 20%;">Fecha</th>
    <th scope="col" style="width: 15%;">Opciones</th>
</tr>
{%endblock%}

{%block rows%}
    {% for c in indicacion %}
    <tr>           
        <td>{{c.autor}}</td>
        <td>{{c.titulo}}</td>
        <td>{{c.descripcion}}</td>
        <td>{{c.fecha}}</td>  
        <td>
        {% for g in request.user.groups.all %}
            {% if g.name == "Docente" %}
                <a href="/srea/ad_asignatura/{{c.id}}/" class="btn btn-warning btn-xs btn-flat"><i class="fas fa-edit"></i></a>
                <a href="/srea/d_asignatura/{{c.id}}" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>
            {% endif %}
        {% endfor %}
        {% if request.user.is_staff %}
            <a href="/srea/ad_asignatura/{{c.id}}/" class="btn btn-warning btn-xs btn-flat"><i class="fas fa-edit"></i></a>
            <a href="/srea/d_asignatura/{{c.id}}" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>
        {% endif %} 
        <a href="/srea/asignatura/{{c.id}}/user/" class="btn btn-primary btn-xs"><i class="fa fa-search"> Ver</i></a>
        </td><!--/user/facultad_list/u_facultad/{{f.id}}ddddd{{request.user.id}}-->
        </tr>
    {% endfor %}
{%endblock%}

{% block javascript %}
<script type="application/javascript">
    $(function(){
        $('#data').DataTable({
          responsive: true,
          autoWidth: false
        });
    });
</script>

{% endblock  %}