apps/srea/urls.py
from django.urls import path
from .vistas.asignatura import *
from .vistas.curso import *
from .vistas.unidad import *
from .vistas.catalogo import *
from .vistas.catalago_item import *
from .vistas.mensaje import *
from .vistas.user_quiz import *

from apps.quiz.views import*
from .vistas.file import *

######################################################
from django.views import View
######################################################

from django.contrib.auth.decorators import login_required

app_name="apps.srea" #Variable que me permite decir como se va a llamar la ruta que se va a concatenar con la otra ruta absoluta

urlpatterns = [
#-------------------------------home---------------------------------------#
    path('index1/',presentarResultadoUsuario, name="index1"), #IndexView.as_view()--->Revisar este método
   

#-------------------------Asignatura-----------------------------------------
    path('a_lista/',AsignaturaListView.as_view(), name="p_asignatura"), #principal_asignatura
    path('asignatura/',AsignaturaCreateView.as_view(), name="asignatura"), #crear asignatura
    path('ad_asignatura/<str:asignatura_id>/', AsignaturaUpdateView, name="u_asignatura"),
    path('d_asignatura/<str:pk>/', AsignaturaDeleteView.as_view(), name="d_asignatura"),
    #######################################Acceder a cada asignatura##############################################
    path('asignatura/<str:asignatura_id>/user/', AsignaturaDetail, name='course'),

    path('<str:asignatura_id>/matricula-lista/<int:user_id>/', MatricularLista, name='matricula-lista'),
    path('<asignatura_id>/enroll/<int:user_id>/matricular', Matricular, name='enroll'),
    #ListarEstudiantes
    path('estudiantes/<str:asignatura_id>/', ListarEstudiantes, name='estudiantes'),
#-------------------------Unidad-----------------------------------------WS
    path('<asignatura_id>/unidades/',AsignaturaUnidades, name="primeraU"),
    path('<asignatura_id>/unidades/newunidades',NewModule, name="unidad"), #crear unidad
    path('<asignatura_id>/<str:unidad_id>/unidades/act_unidad/', EditMudule, name="act-unidad"),
    path('u_unidad/d_unidad/<str:pk>/', UnidadDeleteView.as_view(), name="delete_unidad"),
#-------------------------Ciclo-----------------------------------------
    path('ciclo/',CursoListView.as_view(), name="curso"),
    path('matricula/',CursoCreateView.as_view(), name="r_curso"),
    path('matricula/u_matricula/<int:pk>/', CursoUpdateView.as_view(), name="u_curso"),
    path('matricula/d_matricula/<int:pk>/', CursoDeleteView.as_view(), name="d_curso"),

    #-----------------------------------QUIZ--------------------------------------------------
    path('registrar/<str:asignatura_id>/unidades/quiz/', RegistrarQuiz,name='registrar-quiz'),
     path('registrar/<str:asignatura_id>/user/quiz/', RegistrarQuizUser,name='registrar-quiz-user'),


    path('<str:asignatura_id>/unidades/<str:unidad_id>/quiz/<int:quiz_id>/take/edit', EditQuiz,name='edit-quiz'),

    path('<str:asignatura_id>/unidades/<str:unidad_id>/quiz/<int:quiz_id>/<int:question_id>/take/edit', EditQuestion,name='edit-question'),
    path('<str:asignatura_id>/unidades/<str:unidad_id>/quiz/<int:quiz_id>/<int:question_id>/<int:answer_id>/take/edit', EditAnswer,name='edit-answer'),    
    
    
    path('<asignatura_id>/unidades/<str:unidad_id>/quiz/<int:external_id>/', QuizDetail, name='quiz-detail'),
    path('<asignatura_id>/unidades/<str:unidad_id>/quiz/<quiz_id>/take', TakeQuiz, name='take-quiz'),
    path('<asignatura_id>/unidades/<str:unidad_id>/quiz/<quiz_id>/take/submit', SubmitAttempt, name='submit-quiz'),

    ##################################Guardar quiz de user#################################################
     path('<asignatura_id>/unidades/quiz/<int:external_id>/', QuizDetailUser, name='quiz-detail-user'),

     path('<asignatura_id>/unidades/quiz/<quiz_id>/take', TakeQuizUser, name='take-quiz-user'),
     path('<asignatura_id>/unidades/quiz/<quiz_id>/take/submit', SubmitAttemptUser, name='submit-quiz-user'),

    ###Usado para Js
    path('<asignatura_id>/unidades/<str:unidad_id>/quiz/<quiz_id>/take/data', TakeQuiz2, name='take-data'),


    #######################################CATALOGO####################################################
    path('catalogo/',CatalogListView.as_view(), name="catalogo"), #presentar
    path('catalogo_crear/',CatalogoCreateView.as_view(), name="catalogo_create"), #crear
    path('catalogo/catalogo_edit/<int:pk>/',CatalogoUpdateView.as_view(), name="catalogo_edit"), #editar
    path('catalogo/catalogo_delete/<int:pk>/', CatalogoDeleteView.as_view(), name="catalogo_delete"),
     #######################################CATALOGO ITEM####################################################
    path('catalogo_item/',CatalogItemListView.as_view(), name="catalogo_item"), #presentar
    path('catalogo_item_crear/',CatalogoItemCreateView.as_view(), name="catalogo_item_create"), #crear
    path('catalogo/catalogo_item_edit/<int:pk>/',CatalogoItemUpdateView.as_view(), name="catalogo_item_edit"), #editar
    path('catalogo/catalogo_item_delete/<int:pk>/', CatalogoItemDeleteView.as_view(), name="catalogo_item_delete"),

    ##########################################MENSAJES#######################################################3
    path('mensaje_asignatura/<asignatura_id>/',MensajeAsignatura, name="mensaje_asignatura"), #presentar
    path('crear_mensaje_asignatura/<asignatura_id>/', MensajeCreate, name='crear_mensajes'),
    path('editar_mensaje_asignatura/<asignatura_id>/<str:mensajenasignatura_id>/', MensajeUpdateView, name='editar_mensajes'),
    path('eliminar_mensaje_asignatura/<str:asignatura_id>/<str:mensajenasignatura_id>/', EliminarMensaje, name='eliminar_mensajes'),
    #Mensaje-------------------->Acceder a cada mensaje
    path('mesajes_asignatura/<str:mensajenasignatura_id>/', MensajeDetail, name='ver_mensajes'),


    #-------------------------File-----------------------------------------
    path('file/',FileListView.as_view(), name="p_file"), #principal_asignatura
]

core/urls.py
from django.contrib import admin #Librería de adminitración
from django.urls import path, include #Librería permite incluir las urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.login.urls'),  name='login1'),
    path('admin/', admin.site.urls),#Al inicio cargamos el administrador de Django
    path('accounts/', include('allauth.urls')),
    path('srea/',include('apps.srea.urls', namespace='srea')),
    path('user/',include('apps.user.urls', namespace='user')),
    path('quiz/',include('apps.quiz.urls', namespace='quiz')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #Configuracón para que se puedan leer los archivos

apps/srea/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict # Librería que permite convertir mi modelo a tipo diccionario
from core.settings import MEDIA_URL, STATIC_URL
from apps.srea.tipo_pregunta import tipo_preguntas
from apps.user.models import User
from apps.quiz.models import *
from datetime import date
import  random
import uuid
#from srea.encryption_util import*

class Catalog(models.Model):
    external_id = models.UUIDField(default=uuid.uuid4, editable=False, null=False)
    active = models.BooleanField(null=True, default=True)
    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500) 
    order = models.PositiveSmallIntegerField(null=True)
    createdAt = models.DateTimeField('CreatedAt', auto_now=True, auto_now_add=False)
    updatedAt = models.DateTimeField('UpdatedAt', auto_now=True, auto_now_add=False)

    class Meta:
        db_table = 'catalog'
        verbose_name = 'catalog'
        verbose_name_plural = 'catalogs'
        ordering = ['code', ]

    def __str__(self):
        return self.name


class CatalogItem(models.Model):
    external_id = models.UUIDField(default=uuid.uuid4, editable=False, null=False)
    active = models.BooleanField(null=True, default=True)
    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500) 
    order = models.PositiveSmallIntegerField(null=True)
    createdAt = models.DateTimeField('CreatedAt', auto_now=True, auto_now_add=False)
    updatedAt = models.DateTimeField('UpdatedAt', auto_now=True, auto_now_add=False)
    catalog = models.ForeignKey(Catalog, on_delete=models.CASCADE, related_name="catalog_item")

    class Meta:
        db_table = 'catalog_item'
        verbose_name = 'catalog_item'
        verbose_name_plural = 'catalog_items'
        ordering = ['catalog', 'order', 'name']

    def __str__(self):
        return self.name


class Facultad(models.Model):
	nombre = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
	descripcion =models.TextField(verbose_name='Descripción')
	#carrera = models.ManyToManyField(Carrera, blank=True,related_name="carrera", verbose_name="Carreras")

	###Crear un método llamado toJSON###
	def toJSON(self):##Me devuelve un diccionario con todos los atributos de mi entidad
		item=model_to_dict(self) #Mi atributo self contiene mi modelo
		#item['carrera']=[{'id':g.id, 'nombre':g.nombre}for g  in self.carrera.all()]
		return item

	def __str__(self):
		return self.nombre


class Unidad(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=150, verbose_name='Nombre', unique=False)
    descripcion =models.TextField(verbose_name='Descripción')
    
	
	
    def __str__(self):
	    return self.nombre

################################QUIZ-UNIDAD#########################################
class UnidadQuiz(models.Model):
	quiz=models.ForeignKey(Quiz, related_name="quiz_unidad",verbose_name=("Registrar quiz"), on_delete=models.CASCADE)
	unidad=models.ForeignKey(Unidad, related_name="unidad_quiz",verbose_name=("Registrar unidad"), on_delete=models.CASCADE)



	def __str__(self):
	    return self.quiz.name

################################QUIZ-USUARIO#########################################
class UserQuiz(models.Model):
	quiz=models.ForeignKey(Quiz, related_name="quiz_users",verbose_name=("Registrar quiz"), on_delete=models.CASCADE)
	users=models.ManyToManyField(User,blank=True, related_name="users_quiz",verbose_name=("Registrar usuario"))



	def __str__(self):
	    return self.quiz.name

##################Carrera######################
class Carrera(models.Model):
	facultad = models.ForeignKey(Facultad,on_delete=models.CASCADE, related_name="facultad", verbose_name="Facultad")
	nombre = models.CharField(max_length=50, verbose_name='Nombre', unique=True)
	duracion = models.PositiveSmallIntegerField(verbose_name='Duración', default=5)

	###Crear un método llamado toJSON###
	def toJSON(self):##Me devuelve un diccionario con todos los atributos de mi entidad
		item=model_to_dict(self) #Mi atributo self contiene mi modelo
		#item['curso']=[{'id':c.id, 'nombre':c.nombre_ciclo}for c  in self.curso.all()]
		return item

	def __str__(self):
		return self.nombre
	

##################Curso######################
class Ciclo(models.Model): ###-->Ciclos-->Categoria
	nombre_ciclo = models.CharField(max_length=150, verbose_name="Nombre de ciclo")   
	carrera=models.ForeignKey(Carrera,on_delete=models.CASCADE, related_name="carrera", verbose_name="Carrera")
	fecha=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de registro")
	

	def get_carrera(self):
		if self.carrera:
				name=str(self.carrera.nombre)
				#print(name)
				return name
		return ''
	
	def get_carrera_ciclo(self):
		if self.ciclo:
				name=str(self.ciclo.nombre)
				#print(name)
				return name
		return ''

		###Crear un método llamado toJSON###
	def toJSON(self):##Me devuelve un diccionario con todos los atributos de mi entidad
		item=model_to_dict(self) #Mi atributo self contiene mi modelo, se convierte en un diccionario
		item['fecha']=self.fecha.strftime('%Y-%m-%d')
		item['carrera']=self.get_carrera()
		#item['asignatura']=[{'id':c.id, 'nombre':c.nombre}for c  in self.asignatura.all()]
		return item

	def __str__(self):
		return str(self.nombre_ciclo)
	
	class Meta:
		verbose_name = 'Ciclo'
		verbose_name_plural = 'Ciclos'
		ordering = ['id'] 


##################Asignatura######################    
class Asignatura(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	nombre=models.CharField(max_length=150, verbose_name='Nombre', unique=True)
	detalle=models.TextField(verbose_name='Detalle de la asignatura')
	imagen = models.ImageField(upload_to='asignatura/%Y/%m/%d', null=True, blank=True)
	ciclo=models.ForeignKey(Ciclo,on_delete=models.CASCADE, related_name="ciclo", verbose_name="Ciclo")
	users= models.ManyToManyField(User,blank=True,related_name="users", verbose_name="Usuario" )#Matriculados
	unidad= models.ManyToManyField(Unidad,blank=True,related_name="unidad_asignatura", verbose_name="Unidad" )
  
	def get_image(self):
		if self.imagen:
			return '{}{}'.format(MEDIA_URL, self.imagen)
		return '{}{}'.format(STATIC_URL, 'img/usuario.png')

	def get_curso(self):
		if self.users.all():
			for u in self.users.all():
				for g in u.groups.all():
					if g.name=="Docente":
						name=str(u.get_full_name())
						#print("-->",name)
						return name
		return ''
	#def get_usuarios(self):
	#	users=self.users
	#	users['users'] = [{'id':u.id, 'username':u.username}for u  in self.users.all()]
		#name=str(self.users)
		#print(users)
	#	return users
	#	return ''
			
		#return '{}{}'.format(STATIC_URL, 'img/usuario.png')
		
#    def get_unidad(self):
#        unidad_objs=list(Unidad.objects.filter(asignaturas=self))
#        data = []
#        for u_obj  in unidad_objs:
#            data.append(u_obj)
#        return data
	
	 ###Crear un método llamado toJSON###
	def toJSON(self):##Me devuelve un diccionario con todos los atributos de mi entidad
		item = model_to_dict(self, exclude=['usuario'])
		item['imagen']=self.get_image()
		#item['perfil']=self.get_user_imagen()
		item['users']=[{'id':u.id, 'username':u.username,'groups':u.groups.all, 'firts_name':u.first_name,'last_name':u.last_name, 'imagen':u.imagen}for u  in self.users.all()]
		item['unidad']=[{'id':u.id, 'nombre':u.nombre}for u  in self.unidad.all()]
		#print(item)

		return item

	def __str__(self):
		return self.nombre 

	class Meta:
		verbose_name = 'Asignatura'
		verbose_name_plural = 'Asignaturas'
		ordering = ['id']   

##############################################

class MensajenAsignatura(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	asignatura= models.ForeignKey(Asignatura,blank=True,on_delete=models.CASCADE,related_name="asignatura", verbose_name="Asignatura")
	titulo=models.CharField(max_length=100, verbose_name="Título del mensaje")
	descripcion=models.TextField(max_length=900,blank=True, null=True,verbose_name='Descripción del mensaje')
	fecha=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de publicación del mensaje")
	#user_indicacion=models.ManyToManyField(User,blank=True,related_name="user_ind", verbose_name="Indicación de usuarios" )
	
	def __str__(self):
		return self.titulo
	
	class Meta:
		verbose_name = 'Mensaje'
		verbose_name_plural = 'Mensajes'
		ordering = ['id']

	

class FileUploaded(models.Model):
    nombre=models.CharField(max_length=100, verbose_name="Nombre del archivo")
    file = models.FileField(upload_to='archivo/%Y/%m/%d', null= True, blank= True, verbose_name="Cargar archivo")#donde se va a subir
    observation = models.CharField(max_length=200, null=True, verbose_name='Observación')

    def __str__(self):
        return self.observation

    class Meta:
        db_table = 'file_uploaded'
        verbose_name = 'file_uploaded'
        verbose_name_plural = 'file_uploadeds'
        ordering = ['id']



class SubirArchivos(models.Model):
    nombre=models.CharField(max_length=100, verbose_name="Nombre del archivo")
    archivo = models.FileField(upload_to='formato/%Y/%m/%d', null= True, blank= True, verbose_name="Cargar archivo")#donde se va a subir
    observación = models.CharField(max_length=200, null=True, verbose_name='Observación')

    def __str__(self):
        return self.observación
    

    class Meta:
        verbose_name = 'subir_archivo'
        verbose_name_plural = 'subir_archivos'
        ordering = ['id']





@receiver(pre_save, sender=FileUploaded)
def archivo_cargado_pre_save(sender, instance, **kwargs):
    from apps.quiz.layers.application.service_app_uploaded_archive import ArchivoCargadoAppService
    

apps/srea/templates/mensaje_asignatura/mensaje_create.html
{% extends 'formulario.html' %}
{% load static %}
{% load widget_tweaks %} {#Importamos la librería#}
{% block head %}
    {% block head_form %}
    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
    <script src="{% static 'unidad/forms.js' %}"></script>
    {% endblock%}
{% endblock%} 
{% block content %}
    <form method="post" action="" enctype="multipart/form-data" role="form">
        <div class="card card-primary">
            <div class="card-body">
                {% csrf_token %} <!--Protección de Django-->
                {% for field in form.visible_fields %}<!--Recorrer el formulario a través de la propiedad visible_fields se accede a todos los componentes-->
                    <div class="form-group">
                        <label for="">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" value="login" class="btn btn-info">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{% url 'srea:mensaje_asignatura' asignatura_id  %}"  class="btn btn-danger">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
{% endblock %}

apps/srea/templates/mensaje_asignatura/mensaje_delete.html
{% extends "base_delete.html" %}
{%block title%}Eliminar mensaje{%endblock%}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="alert alert-danger alert-dismissible"> 
        <h5><i class="icon fas fa-trash"></i> Notificación!</h5>
        ¿Desea eliminar el registro de {{mensaje.titulo}}?
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary btn-flat">
            <i class="fas fa-save"></i> Si, aceptar
        </button>
        <a href="/srea/mensaje_asignatura/{{asignatura_id}}/" class="btn btn-info btn-flat">
            <i class="fas fa-times"></i> Cancelar
        </a>
    </div>
</form>
{% endblock content %}

apps/srea/templates/mensaje_asignatura/mensaje_estudiante.html
<style>
    .main_div{
      margin:55px 0;
      with:55%;
      margin:100px auto;
      
    }
    .feed_principal{
      margin-bottom:20px;
      padding-bottom:15px 20px 0;
      background:rgb(200, 200, 180);
      border-radius:5px;
    }
  
  
  
    .titulo_header{
      margin-bottom: 10px
      word-wrap: break-word;
    }
  
    .big{
      margin-right: 5px;
      margin-left: 0px;
      font-weight:bold;
      font-size:19px;
      display:inline;
      line-height: 1.3;
    }
    .feed_propieda{
      display:table;
      width:100%;
    }
    .feed_avatar{
      display:table-cell;
      width:45px;
    }
    .userAvatar{
      background-size:100%;
      position:relative;
      display:block;
      margin-right:15px;
      float:left;
      border-radius:50%;
      width: 35px;
      height:35px;
    }
    .feed_detalles{
      display: table-cell;
      vertical-align:middle;
    }
    .feed_meta{
      color:#b2b2b2;
    }
    .b_comentar{
      outline:none;
      border:none;
      padding:10px;
      blackground:#333;
  
      border-radius:10px;
      display:block;
      margin-right:7px 0;
    }
  </style>

apps/srea/templates/mensaje_asignatura/mensaje_lista.html
{% extends 'base_list.html' %}
{% load widget_tweaks %}
{% load static %}
{%block title%}Lista de Mensajes{%endblock%}
{% block head_list %}
    
{% endblock %}
{%block colums%}
<tr>
    <th scope="col" style="width: 16%;">Titulo</th>
    <th scope="col" style="width: 20%;">Fecha</th>
    <th scope="col" style="width: 15%;">Opciones</th>
</tr>
{%endblock%}

{%block rows%}
    {% for c in mensaje %}
    <tr>           
        <td>{{c.titulo}}</td>
        <td>{{c.fecha}}</td>  
        <td>
        {% if not request.user.is_staff %}
          {% for g in request.user.groups.all %}
            {% if g.name == "Docente" %}
                <a href="/srea/editar_mensaje_asignatura/{{asigna.id}}/{{c.id}}/" class="btn btn-warning btn-xs btn-flat"><i class="fas fa-edit"></i></a>
                <a href="/srea/eliminar_mensaje_asignatura/{{asigna.id}}/{{c.id}}/" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>
            {% endif %}
          {% endfor %}
        {% endif %}
        <button onclick="abrir_modal('{% url 'srea:ver_mensajes' c.id %}')" rel="edit" class="btn btn-primary btn-xs btnAdd"><i class="fa fa-search"> Ver</i></button>
        </td><!--/user/facultad_list/u_facultad/{{f.id}}ddddd{{request.user.id}}-->
        </tr>
    {% endfor %}

    <div class="modal fade" id="edicion" role="dialog">

    </div>
{%endblock%}

{% block buttons_list %}
{% if not request.user.is_staff %}
    {% for g in request.user.groups.all %}
        {% if not g.name == "Estudiante" %}
            <a href="{% url 'srea:crear_mensajes' asigna.id %}" class="btn btn-primary btn-flat btnAdd" style="color: white;">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
        {% endif %}
    {% endfor %}
{% endif %}
    <a href="{{url_list}}" class="btn btn-success btn-flat">
        <i class="fas fa-sync"></i> Actualizar
    </a>
{% endblock %}

{% block javascript %}
    var $ = JQuery.noConflict();
    <script type="application/javascript">
        $(function(){
            $('#data').DataTable({
            responsive: true,
            autoWidth: false
            });
        });

        function abrir_modal(url){
            $('#edicion').load(url, function(){
                $(this).modal('show');
            });
        }
    </script>
{% endblock %}

apps/srea/templates/mensaje_asignatura/mensaje_lista_user.html
        <form method="#" action="#" enctype="multipart/form-data">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            <b><i class="fas fa-comment">Mensaje</i><span></span></b>
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <!--<input name="action" type="hidden" value="add">-->
                            <h5><b>Título:</b></h5>
                                <p>{{mensaje.titulo}}</p>
                            <h6><b>Descripción:</b></h6>
                                <p>{{mensaje.descripcion}}</p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="#" class="btn btn-primary btn-flat btn-block"></button>
                    </div>
                </div>
            </div>
        </form>