apps/login/urls.py
from django.contrib import admin
from django.urls import *
from apps.login.views import *


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',LoginFormView.as_view(),  name='login'), #Permite ingresar al administrador
    path('logout/',LogoutRedirectView.as_view(), name='logout'), #Permite salir del administrador
    path('reset/password',ResetPasswordView.as_view(), name='reset_password'), #Permite resetear la clave
    path('change/password/<str:token>/',ChangePasswordView.as_view(), name='change_password'), #Permite crear el formulario para cambiar la clave
]

apps/user/urls.py
from django.urls import path
from apps.user.views import *
from apps.srea.vistas.facultad import*
from apps.user.vistas.carerra import*
from apps.user.vistas.ficha import*
from apps.user.vistas.indicacion import*


from django.contrib.auth.decorators import login_required

app_name="apps.user" #Variable que me permite decir como se va a llamar la ruta que se va a concatenar con la otra ruta absoluta

urlpatterns = [
#-------------------------Usuario---------------------------------------
    path('user_list/',(UserListView.as_view()), name="user_list"),
    path('user/', (UserCreateView.as_view()), name="user"),
    path('user_list/u_user/<int:pk>/', UserUpdateView.as_view(), name="u_user"),
    path('user_list/d_user/<int:pk>/', UserDeleteView.as_view(), name="d_user"),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('perfil/', UserProfileView.as_view(), name='editar_perfil'),
    path('password/', UserChangePasswordView.as_view(), name='cambiar_clave'),

    ########################################################################3
    path('user/login', (UserCreateView2.as_view()), name="user_login"),
#-------------------------Facultad---------------------------------------
    path('facultad_list/',(FacultadListView.as_view()), name="facultad_list"),
    path('facultad/', (FacultadCreateView.as_view()), name="facultad"),
    path('facultad_list/u_facultad/<int:pk>/', FacultadUpdateView.as_view(), name="u_facultad"),
    path('facultad_list/d_facultad/<int:pk>/', FacultadDeleteView.as_view(), name="d_facultad"),

#-------------------------Carrera---------------------------------------
    path('carrera_list/',(CarreraListView.as_view()), name="carrera_list"),
    path('carrera/', (CarreraCreateView.as_view()), name="carrera"),
    path('carrera_list/u_carrera/<int:pk>/', CarreraUpdateView.as_view(), name="u_carrera"),
    path('carrera_list/d_carrera/<int:pk>/', CarreraDeleteView.as_view(), name="d_carrera"),

    #-------------------------Ficha---------------------------------------
    path('ficha_list/',(FichaListView.as_view()), name="ficha_list"),
    path('ficha/', (FichaCreateView.as_view()), name="ficha"),
    path('ficha_list/u_ficha/<str:uuid>/',FichaUpdateView.as_view(), name="u_ficha"),
     path('ficha_list/actualizar_ficha/<str:uuid>/',FichaUsuarioView.as_view(), name="usuario_ficha"),
    path('ficha_list/d_ficha/<str:uuid>/', FichaDeleteView.as_view(), name="d_ficha"),

    ###################################PDF###########################################
     path('ficha_list/pdf/<str:uuid>/', FichaPdfView.as_view(), name="ficha_pdf"),

     ###################################Inicaciones###########################################
     path('indicacion/', IndicacionListView.as_view(), name="ayuda"),

    #path('indicacion/<indicacion_id>', AyudaLista, name="lista-ayuda"),


]

core/urls.py
from django.contrib import admin #Librería de adminitración
from django.urls import path, include #Librería permite incluir las urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('apps.login.urls'),  name='login1'),
    path('admin/', admin.site.urls),#Al inicio cargamos el administrador de Django
    path('accounts/', include('allauth.urls')),
    path('srea/',include('apps.srea.urls', namespace='srea')),
    path('user/',include('apps.user.urls', namespace='user')),
    path('quiz/',include('apps.quiz.urls', namespace='quiz')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #Configuracón para que se puedan leer los archivos

apps/login/models.py
from django.db import models

# Create your models here.

apps/login/forms.py
from django import forms
from apps.user.models import*

class ResetPasswordForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Ingrese su nombre de usuario',
        'class' : 'form-control',
        'autocomplete':'off'
    }))

    def clean(self):
        cleaned = super().clean()
        if not User.objects.filter(username=cleaned['username']).exists():
            self._errors['error'] = self._errors.get('error', self.error_class())
            self._errors['error'].append('El usuario no existe')
            #raise forms.ValidationError('El usuario no existe')
        return cleaned

    def get_user(self):
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)

class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Ingrese su clave',
        'class' : 'form-control',
        'autocomplete':'off'
    }))

    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Ingrese su clave nuevamente',
        'class' : 'form-control',
        'autocomplete':'off'
    }))

    def clean(self):
        cleaned = super().clean()
        password = cleaned['password']
        confirmPassword = cleaned['confirmPassword']
        if password != confirmPassword:
            self._errors['error'] = self._errors.get('error', self.error_class())
            self._errors['error'].append('No coinciden las claves')
        return cleaned

        

apps/login/views.py
from django.contrib.auth.views import LoginView,LogoutView
from django.shortcuts import *
from django.views.generic import RedirectView,FormView
from django.contrib.auth import logout
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator #importando el método decorador
from django.views.decorators.csrf import csrf_exempt
from apps.login.forms import*
from django.http import *
import smtplib
import uuid #Permite generar un código universal de encriptación
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.template.loader import render_to_string



class LoginFormView(LoginView):
    template_name='login.html'
    #success_url= reverse_lazy('login:index1') #Me redirecciona la URL y reverse_lazy->devuelve la ruta de la URL
   
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL) #Enviado esa dirección
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title']='Iniciar sesión'
        return context

class LogoutRedirectView(RedirectView):
    pattern_name='login' #El nombre del patrón de URL al que se redirigirá.
    
  
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super().dispatch(request, *args, **kwargs)

class ResetPasswordView(FormView):
    form_class = ResetPasswordForm
    template_name= 'login/reset_password.html'
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    
    @method_decorator(csrf_exempt)#Mecanismo de defensa de django
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def send_email_reset_pwd(self, user):
            data = {}
            try:
                URL = settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']
                user.token = uuid.uuid4()
                user.save()

                mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
                mailServer.starttls()
                mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

                email_to = user.email
                mensaje = MIMEMultipart()
                mensaje['From'] = settings.EMAIL_HOST_USER
                mensaje['To'] = email_to
                mensaje['Subject'] = 'Reseteo de contraseña'

                content = render_to_string('login/send_email.html', {
                    'user': user,
                    'link_resetpwd': 'http://{}/change/password/{}/'.format(URL, str(user.token)),
                    'link_home': 'http://{}'.format(URL)
                })
                mensaje.attach(MIMEText(content, 'html'))

                mailServer.sendmail(settings.EMAIL_HOST_USER,
                                    email_to,
                                    mensaje.as_string())
            except Exception as e:
                data['error'] = str(e)
            return data

    def post(self, request, *args, **kwargs):###Implementación de ajax en mi método sobrescrito POST###
        data={} #Se declara un diccionario llamado data
        try: #controlar el error
            form = ResetPasswordForm(request.POST)
            if form.is_valid():
                user=form.get_user()
                data=self.send_email_reset_pwd(user)
            else:
                data['error'] =form.errors
        except Exception as e: #Llamamos a la clase Exceptio para indicar el error
            data['error']=str(e) #Me devuelve el objeto e-->convertido a un string
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title']='Reseteo de Clave'
        return context
    

class ChangePasswordView(FormView):
    form_class = ChangePasswordForm
    template_name= 'login/change_password.html'
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    
    @method_decorator(csrf_exempt)#Mecanismo de defensa de django
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        if User.objects.filter(token=token).exists():
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect('/')

    def post(self, request, *args, **kwargs):###Implementación de ajax en mi método sobrescrito POST###
        data={} #Se declara un diccionario llamado data
        try: #controlar el error
            form = ChangePasswordForm(request.POST)
            if form.is_valid():
                user = User.objects.get(token=self.kwargs['token'])
                user.set_password(request.POST['password'])
                user.token = uuid.uuid4()
                user.save()
            else:
                data['error'] =form.errors
        except Exception as e: #Llamamos a la clase Exceptio para indicar el error
            data['error']=str(e) #Me devuelve el objeto e-->convertido a un string
        return JsonResponse(data,safe=False)

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title']='Reseteo de Clave'
        return context
    

apps/login/templates/footer2.html
<style>
    footer {
      text-align: center;
      padding: 3px;
      color: black;
    }
</style>

<footer id="footer" class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline"></div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022-2023 <a href="#">Henrry</a>.</strong> Todos los
    derechos reservados
</footer>

apps/login/templates/login.html
{% extends 'login_base.html' %}
{% load socialaccount %}
{% load widget_tweaks %}

{% block content %}
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Bienvenido</p>
      <!-- formulario -->
      <form action="." method="post">
        <input type="hidden" name="next" value="{{ next }}" /> <!-- Permite verificar el atributo next -->
        {% csrf_token %}
        <div class="input-group mb-3">
          {{ form.username|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Nombre de usuario' }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          {{ form.password|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Contraseña' }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-sign-in-alt"></i>Iniciar sesión</button>
          </div>
        </div>
        <p class="text-center">
          <a href="{% url 'user:user_login' %}">Crear una cuenta</a>
        </p>
      </form>
      <!-- /.social-auth-links -->
      <div class="social-auth-links text-center mb-0">
        <p>- OR -</p>
       <!-- <a href="#" class="btn-fa-primary">
          <i class="fab fa-facebook mr-2" style='font-size:30px;color:darkblue'></i>
        </a>-->
        <h4>Google</h4>
        <a class="btn-fa-danger" href="{% provider_login_url  "google"  %}">
          <i class="fab fa-google-plus mr-2" style='font-size:30px;color:brown'></i>
        </a>
        <hr>
        <p class="mb-0">
          <a href="{% url 'reset_password' %}">¿Olvidaste tu contraseña?</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

apps/login/templates/login_base.html
{% load static %}
{%load widget_tweaks%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{%block title%} {%endblock%}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
      <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
      <!-- Google Font: Source Sans Pro -->
    <link href="{% static 'css/google-font.css' %}" rel="stylesheet">
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!--Sweetalert2-->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>

    <!--temporizador-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    
    {% block head %}

    {% endblock %}

    {% block extra_head %}
    {% endblock %}
        
</head>
<body>
<div class="hold-transition login-page">
    {% for message in messages %}
    <div class="message alert-success {{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
  <div class="login-logo"> <!--Logo-->
    <a href="{% url 'login'%}"><b>SREA</b></a>
  </div>
  <div class="card">
    <div class="card-body login-card-body">
    {% block body %}

      {% block content %}
      {% endblock  %}

    {% endblock %}
    </div>
  </div>  
  



{% block extra_body %}
{% endblock %}

<div>

</div>
{% include 'script.html' %}
</div>

</body>

</html>

apps/login/templates/script.html
<script type="application/javascript">
    {% if form.errors %}
        var errors = '';
        {% for field in form %}
            {% for error in field.errors %}
                errors += '{{ error }}\n';
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            errors += '{{ error }}\n';
        {% endfor %}
        Swal.fire({
            title: 'Aviso!',
            text: errors
        });
    {% endif %}
</script> 